In [4]:
#classification

In [5]:
import pandas as pd

In [6]:
#sample Classification data

In [7]:
data={
    "hours_study":[1,2,3,4,5,6,7,8,9,10],
    "passed":[0,0,0,0,0,1,1,1,1,1]
}

In [8]:
data

{'hours_study': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 'passed': [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]}

In [9]:
df = pd.DataFrame(data)

In [10]:
df

   hours_study  passed
0            1       0
1            2       0
2            3       0
3            4       0
4            5       0
5            6       1
6            7       1
7            8       1
8            9       1
9           10       1

In [11]:
x=df[["hours_study"]]
y=df["passed"]

In [12]:
x

   hours_study
0            1
1            2
2            3
3            4
4            5
5            6
6            7
7            8
8            9
9           10

In [13]:
y

0    0
1    0
2    0
3    0
4    0
5    1
6    1
7    1
8    1
9    1
Name: passed, dtype: int64

In [14]:
#split data into traning and testing

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
x_train

   hours_study
5            6
0            1
7            8
2            3
9           10
4            5
3            4
6            7

In [18]:
x_test

   hours_study
8            9
1            2

In [19]:
y_train

5    1
0    0
7    1
2    0
9    1
4    0
3    0
6    1
Name: passed, dtype: int64

In [20]:
y_test

8    1
1    0
Name: passed, dtype: int64

In [21]:
#Import Logistics Regression

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
#create and train model

In [24]:
model = LogisticRegression()

In [25]:
model.fit(x_train,y_train)

LogisticRegression()

In [26]:
#prediction

In [27]:
y_pred = model.predict(x_test)

In [28]:
y_pred

array([1, 0])

In [29]:
y_test

8    1
1    0
Name: passed, dtype: int64

In [30]:
prediction = model.predict([[7.5]])

C:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [31]:
prediction

array([1])

In [34]:
from sklearn.metrics import accuracy_score

In [35]:
accuracy = accuracy_score(y_test,y_pred)

In [36]:
accuracy

1.0

In [37]:
y_prob =  model.predict_proba(x_test)

In [38]:
y_prob

array([[0.01799637, 0.98200363],
       [0.98200563, 0.01799437]])